name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - python
  - pip
  - pytorch
  - torchvision
  - numpy
  - pip:
      - albumentations
      - opencv-python
      - pudb
      - imageio
      - imageio-ffmpeg
      - pytorch-lightning
      - omegaconf
      - test-tube
      - streamlit
      - einops
      - torch-fidelity
      - transformers
      - taming-transformers-rom1504
      - -e .
