model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: 'val/rec_loss'
    embed_dim: 64
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        perceptual_weight: 0 # this function currently works only with rgb
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5
        disc_in_channels: 5 # Changed for JUMP channels

    ddconfig:
      double_z: True
      z_channels: 64
      resolution: 512 # JUMP image size
      in_channels: 5 # JUMP channels
      out_ch: 5 # JUMP channels
      ch: 128
      ch_mult: [1, 2, 4, 8]
      # ch_mult: [1, 2, 4, 8] # needs adjustment for 1080x1080
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

data:
  target: main.WebDataModuleFromConfig
  params:
    batch_size: 1 # Start small due to image size
    num_workers: 1
    train:
      target: ldm.data.jump.JumpWebDataset
      params:
        root: data/jump_wds
        train: True
    validation:
      target: ldm.data.jump.JumpWebDataset
      params:
        root: data/jump_wds
        train: False

lightning:
  trainer:
    benchmark: True
    max_epochs: 20
    accelerator: 'cpu'

  logger:
    - target: pytorch_lightning.loggers.WandbLogger
      params:
        project: 'jump'
