model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.BasicAutoencoderKL
  params:
    monitor: 'val/rec_loss'
    embed_dim: 4
    lossconfig:
      target: ldm.modules.losses.ELBOLoss
      params:
        kl_weight: 0.000001

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 512
      in_channels: 5
      out_ch: 5
      ch: 128
      # ch_mult with length 4 => 3 downsamplings
      #   512 => 256 => 128 => 64
      # giving final shape [4, 64, 64]
      ch_mult: [1, 2, 4, 8]
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

data:
  target: main.WebDataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 1
    train:
      target: ldm.data.jump.JumpWebDataset
      params:
        root: data/cpg0012
        train: True
        batch_size: ${data.params.batch_size}
    validation:
      target: ldm.data.jump.JumpWebDataset
      params:
        root: data/cpg0012
        train: False
        batch_size: ${data.params.batch_size}

lightning:
  trainer:
    benchmark: True
    max_epochs: 100
    accelerator: 'mps'
  logger:
    - target: pytorch_lightning.loggers.WandbLogger
      params:
        project: 'jump'
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        log_first_step: True
        batch_frequency: 100
        max_images: 4
        clamp: True
