model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.BasicAutoencoderKL
  params:
    monitor: 'val/rec_loss'
    embed_dim: 64
    lossconfig:
      target: ldm.modules.losses.ELBOLoss
      params:
        kl_weight: 0

    ddconfig:
      double_z: True
      z_channels: 64
      resolution: 512 # JUMP image size
      in_channels: 5 # JUMP channels
      out_ch: 5 # JUMP channels
      ch: 128
      ch_mult: [1, 1, 2, 2, 4, 4, 8]
      num_res_blocks: 2
      attn_resolutions: [16, 8]
      dropout: 0.0

data:
  target: main.WebDataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 1
    train:
      target: ldm.data.jump.JumpWebDataset
      params:
        root: data/jump_overfit
        train: True
        batch_size: ${data.params.batch_size}
    validation:
      target: ldm.data.jump.JumpWebDataset
      params:
        root: data/jump_overfit
        train: False
        batch_size: ${data.params.batch_size}

lightning:
  trainer:
    benchmark: True
    max_epochs: 150
    accelerator: 'gpu'
  logger:
    - target: pytorch_lightning.loggers.WandbLogger
      params:
        project: 'jump'
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        log_first_step: True
        batch_frequency: 100
        max_images: 4
        clamp: True
